Update ReactiveSwift to 5.0
Carthage/ReactiveTask pull request #112
Opened 2019-03-17 12:47 UTC by mattprowse

2019-03-20 12:21 UTC, mdiep requested changes
The podspec also needs to be updated.

2019-03-20 12:21 UTC, mdiep commented on ReactiveTask.xcodeproj/project.pbxproj
> +				MACOSX_DEPLOYMENT_TARGET = 10.10;
Instead of changing the deployment target for the project/framework, can you change it just for the test target?

2019-03-20 12:21 UTC, mdiep commented
Thanks for taking this on!

2019-03-21 12:08 UTC, mattprowse commented
No worries at all, I'm happy to help! I think I've addressed all of the PR comments. I'm not sure why `pod lib lint` is erroring on Travis though. It's succeeding for me locally.

2019-03-21 12:21 UTC, mdiep approved these changes

2019-03-21 12:22 UTC, mdiep commented
Weird. I think we need to figure that out. Any ideas, @ikesyo?

2019-04-03 00:26 UTC, ikesyo commented
CocoaPods's version is the problem so updated in 291a87a.

2019-04-03 01:08 UTC, ikesyo approved these changes

2019-04-03 01:10 UTC, merged